version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: cimg/node:16.14.2

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Get Hatena
          command: node .circleci/generate_hatena.js
      - run:
          name: Build
          command: yarn generate
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
  deploy:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Get Hatena
          command: node .circleci/generate_hatena.js
      - run:
          name: Build
          command: yarn generate
      - run:
          name: Add ads.txt
          command: echo "google.com, pub-7246355771451460, DIRECT, f08c47fec0942fa0" > dist/ads.txt
      - run: git config user.email "korosuke613+circleci@users.noreply.github.com"
      - run: git config user.name "korosuke613+circleci"
      - add_ssh_keys:
          fingerprints:
            - "ae:8d:b2:b2:4f:ec:bd:7c:d8:23:23:90:8c:fd:b2:5b"
      - run:
          name: Deploy
          command: yarn deploy
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/



workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: main

  cron:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy

  publish:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
