name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        version: 14.x
    - name: yarn install, build
      env:
        HATENA_PASS: ${{ secrets.HATENA_PASS }}
      run: |
        yarn
        node .circleci/generate_hatena.js
        yarn generate
        echo Finish!!!!!!
